### PR TITLE
HTML5 headers added and some bugs removed

### PR DESCRIPTION
**Pull request by BlueAndi**
[Review on Reviewable](https://reviewable.io/reviews/grodansparadis/vscp_html5/3)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/grodansparadis/vscp_html5/pull/3%23issuecomment-106577518%22%2C%20%22https%3A//github.com/grodansparadis/vscp_html5/pull/3%23issuecomment-106578594%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/grodansparadis/vscp_html5/pull/3%23issuecomment-106577518%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Added%20you%20as%20a%20collaborator.%22%2C%20%22created_at%22%3A%20%222015-05-28T19%3A49%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1358883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/grodansparadis%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%20%3Ashipit%3A%20all%20files%20reviewed%2C%20all%20discussions%20resolved%2C%20all%20commit%20checks%20successful.%5CnReviewed%20files%3A%5Cn-%20index.html%20%40%20r1%5Cn-%20lib/vscpwslib.js%20%40%20r1%5Cn-%20testws/epoch_simple.html%20%40%20r1%5Cn-%20testws/event.html%20%40%20r1%5Cn-%20testws/example_lmsensors.html%20%40%20r1%5Cn-%20testws/google_gauge.html%20%40%20r1%5Cn-%20testws/google_line_simple%20-%20Copy.html%20%40%20r1%5Cn-%20testws/google_line_simple.html%20%40%20r1%5Cn-%20testws/google_table.html%20%40%20r1%5Cn-%20testws/index.html%20%40%20r1%5Cn-%20testws/node_discovery.html%20%40%20r1%5Cn-%20testws/progress.html%20%40%20r1%5Cn-%20testws/simpletext.html%20%40%20r1%5Cn-%20testws/slider.html%20%40%20r1%5Cn-%20testws/speedometer.html%20%40%20r1%5Cn-%20testws/statebutton.html%20%40%20r1%5Cn-%20testws/table_dynamic.html%20%40%20r1%5Cn-%20testws/table_static.html%20%40%20r1%5Cn-%20testws/testauth.html%20%40%20r1%5Cn-%20testws/testwsleddigits.html%20%40%20r1%5Cn-%20testws/thermometercelsius.html%20%40%20r1%5Cn-%20testws/variable.html%20%40%20r1%5Cn%5Cn---%5Cn%5Cn%5Cn%5CnComments%20from%20the%20%5Breview%20on%20Reviewable.io%5D%28https%3A//reviewable.io%3A443/reviews/grodansparadis/vscp_html5/3%29%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-28T19%3A53%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1358883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/grodansparadis%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/grodansparadis%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1358883%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/grodansparadis'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/grodansparadis/vscp_html5/pull/3#issuecomment-106577518'>General Comment</a></b>
- <a href='https://github.com/grodansparadis'></a> Added you as a collaborator.
- <a href='https://github.com/grodansparadis'></a> Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- index.html @ r1
- lib/vscpwslib.js @ r1
- testws/epoch_simple.html @ r1
- testws/event.html @ r1
- testws/example_lmsensors.html @ r1
- testws/google_gauge.html @ r1
- testws/google_line_simple - Copy.html @ r1
- testws/google_line_simple.html @ r1
- testws/google_table.html @ r1
- testws/index.html @ r1
- testws/node_discovery.html @ r1
- testws/progress.html @ r1
- testws/simpletext.html @ r1
- testws/slider.html @ r1
- testws/speedometer.html @ r1
- testws/statebutton.html @ r1
- testws/table_dynamic.html @ r1
- testws/table_static.html @ r1
- testws/testauth.html @ r1
- testws/testwsleddigits.html @ r1
- testws/thermometercelsius.html @ r1
- testws/variable.html @ r1
---
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grodansparadis/vscp_html5/3)

<a href='https://www.codereviewhub.com/grodansparadis/vscp_html5/pull/3?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/grodansparadis/vscp_html5/pull/3?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/grodansparadis/vscp_html5/pull/3?approve=0'></a>&nbsp;<a href='https://github.com/grodansparadis/vscp_html5/pull/3'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by grodansparadis** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/grodansparadis/vscp_html5/pull/3'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by grodansparadis** [comment]
Added you as a collaborator.

**Comment by grodansparadis** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- index.html @ r1
- lib/vscpwslib.js @ r1
- testws/epoch_simple.html @ r1
- testws/event.html @ r1
- testws/example_lmsensors.html @ r1
- testws/google_gauge.html @ r1
- testws/google_line_simple - Copy.html @ r1
- testws/google_line_simple.html @ r1
- testws/google_table.html @ r1
- testws/index.html @ r1
- testws/node_discovery.html @ r1
- testws/progress.html @ r1
- testws/simpletext.html @ r1
- testws/slider.html @ r1
- testws/speedometer.html @ r1
- testws/statebutton.html @ r1
- testws/table_dynamic.html @ r1
- testws/table_static.html @ r1
- testws/testauth.html @ r1
- testws/testwsleddigits.html @ r1
- testws/thermometercelsius.html @ r1
- testws/variable.html @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grodansparadis/vscp_html5/3)

**Comment by BlueAndi** [comment]
> Added you as a collaborator.

Ok, thanks. That will make it easier to commit.

**Comment by grodansparadis** [comment]
Andreas Merkle skrev den 2015-05-28 22:06:
>
>     Added you as a collaborator.
>
> Ok, thanks. That will make it easier to commit.
>

Added you on software also while I was at it.

/Ake

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Thanks for the trust!

**Comment by grodansparadis** [comment]
Andreas Merkle skrev den 2015-05-28 22:18:
>
> Thanks for the trust!
>

I still will not agree with you all the time. ;-)  But if people trust 
you with there lives I think I have to trust you to. After all the world 
belongs to the young.

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org


---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
:-)

**Pull request merged**
